import type { Product, Order, WholesaleInquiry } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'p001',
    name: 'Handcrafted Madal — Nepali Folk Drum',
    slug: 'handcrafted-madal-nepali-folk-drum',
    category: 'Percussion',
    subcategory: 'Traditional Drums',
    price: 4500,
    originalPrice: 5800,
    rating: 4.8,
    reviewCount: 124,
    images: [
      'https://images.unsplash.com/photo-1530917203633-106d4a1a0967?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1721179389414-8c3f507e2bc2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1729527110458-950587b5494c?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'The Madal is the heartbeat of Nepali folk music. Hand-carved from a single log of jackfruit wood and wrapped with natural goat skin, this double-headed drum produces warm, resonant tones perfect for traditional and contemporary performances. Each piece is crafted by master artisans in the hills of Kavre.',
    specs: [
      { label: 'Material', value: 'Jackfruit wood, goat skin' },
      { label: 'Length', value: '16 inches (40 cm)' },
      { label: 'Diameter', value: '8 inches (20 cm)' },
      { label: 'Weight', value: '1.2 kg' },
      { label: 'Origin', value: 'Kavre, Nepal' },
      { label: 'Includes', value: 'Carrying strap, tuning guide' },
    ],
    features: ['Hand-carved from single log', 'Natural goat skin heads', 'Traditional leather strap', 'Tuned by master artisan'],
    badge: 'sale',
    inStock: true,
    artisan: 'Hari Bahadur Magar',
    region: 'Kavre',
  },
  {
    id: 'p002',
    name: 'Professional Sarangi — Classical Nepali Fiddle',
    slug: 'professional-sarangi-classical-nepali-fiddle',
    category: 'Traditional Instruments',
    subcategory: 'Bowed Strings',
    price: 8900,
    originalPrice: 11000,
    rating: 4.9,
    reviewCount: 87,
    images: [
      'https://images.unsplash.com/photo-1646765444015-5881f0fab3e8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1465821185615-20b3c2fbf41b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1514649923863-ceaf75b7ec00?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'The Sarangi is one of Nepal\'s most expressive traditional instruments, known for its haunting, vocal-like quality. Carved from tun wood with a goat-skin soundboard and 36 sympathetic strings, this professional-grade Sarangi delivers rich, resonant tones that capture the soul of Nepali classical and folk music.',
    specs: [
      { label: 'Material', value: 'Tun wood, goat skin' },
      { label: 'Strings', value: '3 main, 36 sympathetic' },
      { label: 'Bow', value: 'Horsehair, included' },
      { label: 'Length', value: '24 inches (60 cm)' },
      { label: 'Origin', value: 'Kathmandu, Nepal' },
      { label: 'Includes', value: 'Bow, rosin, soft case' },
    ],
    features: ['36 sympathetic strings', 'Hand-carved tun wood body', 'Horsehair bow included', 'Professional concert grade'],
    badge: 'new',
    inStock: true,
    artisan: 'Ram Sharan Nepali',
    region: 'Kathmandu',
  },
  {
    id: 'p003',
    name: 'Tabla Set — Brass Bayan & Teak Dayan',
    slug: 'tabla-set-brass-bayan-teak-dayan',
    category: 'Percussion',
    subcategory: 'Hand Drums',
    price: 7500,
    rating: 4.7,
    reviewCount: 156,
    images: [
      'https://images.unsplash.com/photo-1721179389414-8c3f507e2bc2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1530917203633-106d4a1a0967?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A professional tabla set featuring a brass bayan (left drum) and a teak wood dayan (right drum). Hand-tuned by skilled craftsmen, this set produces the crisp, nuanced tones required for classical Indian and Nepali music. Includes cushion, rings, and hammer.',
    specs: [
      { label: 'Bayan Material', value: 'Brass, copper base' },
      { label: 'Dayan Material', value: 'Teak wood' },
      { label: 'Dayan Pitch', value: 'C (Sa)' },
      { label: 'Heads', value: 'Goat skin, composite rim' },
      { label: 'Origin', value: 'Bhaktapur, Nepal' },
      { label: 'Includes', value: 'Cushion, rings, tuning hammer' },
    ],
    features: ['Brass bayan with rich bass', 'Teak dayan with crisp tone', 'Hand-tuned by master craftsman', 'Complete accessory kit'],
    badge: 'trending',
    inStock: true,
    artisan: 'Surya Prasad Sharma',
    region: 'Bhaktapur',
  },
  {
    id: 'p004',
    name: 'Sitar — Professional Concert Model',
    slug: 'sitar-professional-concert-model',
    category: 'String Instruments',
    subcategory: 'Plucked Strings',
    price: 18500,
    originalPrice: 22000,
    rating: 4.9,
    reviewCount: 64,
    images: [
      'https://images.unsplash.com/photo-1465821185615-20b3c2fbf41b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1646765444015-5881f0fab3e8?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A professional-grade sitar crafted from seasoned tun wood with a calabash gourd resonator. Featuring 13 sympathetic strings and traditional hand-carved bridges, this sitar delivers the deep, resonant tones essential for classical ragas and contemporary fusion.',
    specs: [
      { label: 'Body Wood', value: 'Seasoned tun wood' },
      { label: 'Gourd', value: 'Calabash, natural' },
      { label: 'Strings', value: '7 main, 13 sympathetic' },
      { label: 'Frets', value: 'Brass, 20 frets' },
      { label: 'Origin', value: 'Kathmandu, Nepal' },
      { label: 'Includes', value: 'Hard case, extra strings, mizrabs' },
    ],
    features: ['Seasoned tun wood body', '13 sympathetic strings', 'Calabash gourd resonator', 'Professional concert grade'],
    badge: 'sale',
    inStock: true,
    artisan: 'Ram Sharan Nepali',
    region: 'Kathmandu',
  },
  {
    id: 'p005',
    name: 'Tungna — Traditional Himalayan Lute',
    slug: 'tungna-traditional-himalayan-lute',
    category: 'Traditional Instruments',
    subcategory: 'Plucked Strings',
    price: 6200,
    rating: 4.6,
    reviewCount: 42,
    images: [
      'https://images.unsplash.com/photo-1514649923863-ceaf75b7ec00?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1646765444015-5881f0fab3e8?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'The Tungna is a traditional lute from the Himalayan regions of Nepal, played by the Tamang and Gurung communities. Carved from a single piece of wood with four strings and a skin soundboard, it produces bright, melodic tones perfect for folk songs and cultural ceremonies.',
    specs: [
      { label: 'Material', value: 'Udumber wood, goat skin' },
      { label: 'Strings', value: '4 (steel)' },
      { label: 'Length', value: '28 inches (70 cm)' },
      { label: 'Tuning', value: 'Open chord, folk style' },
      { label: 'Origin', value: 'Lamjung, Nepal' },
      { label: 'Includes', value: 'Picks, tuning key, soft bag' },
    ],
    features: ['Single-piece carved body', 'Goat skin soundboard', 'Traditional Himalayan design', 'Hand-painted detailing'],
    badge: 'new',
    inStock: true,
    artisan: 'Hari Bahadur Magar',
    region: 'Lamjung',
  },
  {
    id: 'p006',
    name: 'Acoustic Ukulele — Mango Wood Soprano',
    slug: 'acoustic-ukulele-mango-wood-soprano',
    category: 'Guitars',
    subcategory: 'Ukuleles',
    price: 3800,
    originalPrice: 4500,
    rating: 4.8,
    reviewCount: 203,
    images: [
      'https://images.unsplash.com/photo-1707699164633-0e584b2da329?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1672578249566-3f4b6d564aa2?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A beautiful soprano ukulele crafted from Nepali mango wood. Warm, bright tone with excellent projection. Features a rosewood fingerboard, quality geared tuners, and a smooth satin finish. Perfect for beginners and experienced players alike.',
    specs: [
      { label: 'Top Wood', value: 'Mango wood' },
      { label: 'Body', value: 'Mango wood' },
      { label: 'Fingerboard', value: 'Rosewood' },
      { label: 'Scale Length', value: '13 inches (soprano)' },
      { label: 'Tuners', value: 'Geared, chrome' },
      { label: 'Includes', value: 'Gig bag, picks, extra strings' },
    ],
    features: ['Solid mango wood top', 'Rosewood fingerboard', 'Geared chrome tuners', 'Satin finish'],
    badge: 'sale',
    inStock: true,
    artisan: 'Bishnu Gurung',
    region: 'Pokhara',
  },
  {
    id: 'p007',
    name: 'Acoustic Guitar — Dreadnought Spruce Top',
    slug: 'acoustic-guitar-dreadnought-spruce-top',
    category: 'Guitars',
    subcategory: 'Acoustic Guitars',
    price: 9500,
    rating: 4.7,
    reviewCount: 178,
    images: [
      'https://images.unsplash.com/photo-1514649923863-ceaf75b7ec00?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1646765444015-5881f0fab3e8?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A full-size dreadnought acoustic guitar with a solid spruce top and mahogany back and sides. Rich, balanced tone with strong projection. Built in our Kathmandu workshop with a comfortable neck profile and flawless fretwork.',
    specs: [
      { label: 'Top', value: 'Solid Sitka spruce' },
      { label: 'Back & Sides', value: 'Mahogany' },
      { label: 'Neck', value: 'Mahogany, 25.5" scale' },
      { label: 'Fingerboard', value: 'Rosewood, 20 frets' },
      { label: 'Body Shape', value: 'Dreadnought' },
      { label: 'Includes', value: 'Hard case, strap, picks' },
    ],
    features: ['Solid spruce top', 'Mahogany back and sides', 'Dreadnought body shape', 'Professional setup included'],
    badge: 'trending',
    inStock: true,
    artisan: 'Bishnu Gurung',
    region: 'Pokhara',
  },
  {
    id: 'p008',
    name: 'Classical Guitar — Cedar Top with Nylon Strings',
    slug: 'classical-guitar-cedar-top-nylon-strings',
    category: 'Guitars',
    subcategory: 'Classical Guitars',
    price: 7200,
    rating: 4.6,
    reviewCount: 91,
    images: [
      'https://images.unsplash.com/photo-1672578249566-3f4b6d564aa2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1514649923863-ceaf75b7ec00?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A classical guitar with a warm cedar top and cypress back and sides. Nylon strings produce the soft, mellow tones ideal for classical, flamenco, and fingerstyle playing. Hand-built with traditional Spanish heel construction.',
    specs: [
      { label: 'Top', value: 'Solid cedar' },
      { label: 'Back & Sides', value: 'Cypress' },
      { label: 'Neck', value: 'Cedar, 650mm scale' },
      { label: 'Fingerboard', value: 'Rosewood, 19 frets' },
      { label: 'Strings', value: 'Nylon, high tension' },
      { label: 'Includes', value: 'Gig bag, footstool' },
    ],
    features: ['Solid cedar top', 'Spanish heel construction', 'Nylon strings included', 'Warm classical tone'],
    inStock: true,
    artisan: 'Bishnu Gurung',
    region: 'Pokhara',
  },
  {
    id: 'p009',
    name: 'Murali Bamboo Flute — Bansuri Professional',
    slug: 'murali-bamboo-flute-bansuri-professional',
    category: 'Wind Instruments',
    subcategory: 'Flutes',
    price: 1200,
    originalPrice: 1800,
    rating: 4.8,
    reviewCount: 312,
    images: [
      'https://images.unsplash.com/photo-1672578249566-3f4b6d564aa2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1530917203633-106d4a1a0967?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A professional bansuri bamboo flute hand-crafted from aged Nepali bamboo. Precisely tuned to the key of C, this murali produces pure, haunting tones that are central to Nepali and Indian classical music. Each flute is tested for pitch accuracy and tonal balance.',
    specs: [
      { label: 'Material', value: 'Aged bamboo' },
      { label: 'Key', value: 'C (Sa)' },
      { label: 'Length', value: '15 inches (38 cm)' },
      { label: 'Holes', value: '6 finger, 1 embouchure' },
      { label: 'Origin', value: 'Dharan, Nepal' },
      { label: 'Includes', value: 'Cloth pouch, cleaning rod' },
    ],
    features: ['Aged Nepali bamboo', 'Precise pitch tuning', 'Professional concert quality', 'Traditional 6-hole design'],
    badge: 'sale',
    inStock: true,
    artisan: 'Mohan Krishna Rai',
    region: 'Dharan',
  },
  {
    id: 'p010',
    name: 'Dholak — Double-Headed Folk Drum',
    slug: 'dholak-double-headed-folk-drum',
    category: 'Percussion',
    subcategory: 'Folk Drums',
    price: 5500,
    rating: 4.5,
    reviewCount: 68,
    images: [
      'https://images.unsplash.com/photo-1721179389414-8c3f507e2bc2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1530917203633-106d4a1a0967?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A traditional dholak handcrafted from neem wood with two goat-skin heads. Produces a deep, resonant bass on one side and a sharp treble on the other. Essential for folk music, bhajans, and festive celebrations across Nepal.',
    specs: [
      { label: 'Material', value: 'Neem wood, goat skin' },
      { label: 'Length', value: '20 inches (50 cm)' },
      { label: 'Heads', value: '2 (bass + treble)' },
      { label: 'Weight', value: '2.5 kg' },
      { label: 'Origin', value: 'Janakpur, Nepal' },
      { label: 'Includes', value: 'Tuning wrench, strap' },
    ],
    features: ['Neem wood body', 'Dual goat-skin heads', 'Traditional rope tuning', 'Rich bass and treble tones'],
    inStock: true,
    artisan: 'Surya Prasad Sharma',
    region: 'Janakpur',
  },
  {
    id: 'p011',
    name: 'Harmonium — Portable Folding Model',
    slug: 'harmonium-portable-folding-model',
    category: 'Keyboards',
    subcategory: 'Harmoniums',
    price: 12500,
    originalPrice: 15000,
    rating: 4.7,
    reviewCount: 134,
    images: [
      'https://images.unsplash.com/photo-1530917203633-106d4a1a0967?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1721179389414-8c3f507e2bc2?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A portable folding harmonium with 3.5 octaves and a coupler function. Crafted from teak wood with a rich, warm tone. Folds into a compact case for easy transport — ideal for traveling musicians, kirtan, and classical vocal practice.',
    specs: [
      { label: 'Keys', value: '42 (3.5 octaves)' },
      { label: 'Reeds', value: 'Double reed' },
      { label: 'Body', value: 'Teak wood' },
      { label: 'Bellows', value: 'Multi-fold, hand-stitched' },
      { label: 'Features', value: 'Coupler, octave shift' },
      { label: 'Includes', value: 'Folding case, cover' },
    ],
    features: ['3.5 octave keyboard', 'Double reed system', 'Folding portable design', 'Coupler function'],
    badge: 'sale',
    inStock: true,
    artisan: 'Ram Sharan Nepali',
    region: 'Kathmandu',
  },
  {
    id: 'p012',
    name: 'Tanpura — Female Tun Miraj Style',
    slug: 'tanpura-female-tun-miraj-style',
    category: 'String Instruments',
    subcategory: 'Drone Strings',
    price: 14500,
    rating: 4.8,
    reviewCount: 47,
    images: [
      'https://images.unsplash.com/photo-1465821185615-20b3c2fbf41b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1646765444015-5881f0fab3e8?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A female tanpura in the Miraj style, crafted from tun wood with a calabash gourd. Produces the rich, sustained drone essential for classical vocal and instrumental performances. Four strings tuned to Sa-Pa-Sa-Sa for perfect harmonic foundation.',
    specs: [
      { label: 'Body', value: 'Tun wood' },
      { label: 'Gourd', value: 'Calabash, natural' },
      { label: 'Strings', value: '4 (steel & brass)' },
      { label: 'Scale', value: 'Female, ~36 inches' },
      { label: 'Bridge', value: 'Hand-carved bone' },
      { label: 'Includes', value: 'Soft case, extra strings' },
    ],
    features: ['Miraj style construction', 'Calabash gourd resonator', '4-string drone tuning', 'Hand-carved bone bridge'],
    badge: 'new',
    inStock: true,
    artisan: 'Ram Sharan Nepali',
    region: 'Kathmandu',
  },
  {
    id: 'p013',
    name: 'Jhyali — Nepali Bronze Cymbals',
    slug: 'jhyali-nepali-bronze-cymbals',
    category: 'Percussion',
    subcategory: 'Cymbals',
    price: 3200,
    rating: 4.6,
    reviewCount: 55,
    images: [
      'https://images.unsplash.com/photo-1530917203633-106d4a1a0967?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1721179389414-8c3f507e2bc2?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'Traditional Nepali bronze cymbals used in Newari devotional and ceremonial music. Hand-forged from a bronze alloy that produces bright, sustained tones. Played by striking the edges together in rhythmic patterns unique to the Kathmandu Valley tradition.',
    specs: [
      { label: 'Material', value: 'Bronze alloy' },
      { label: 'Diameter', value: '6 inches (15 cm)' },
      { label: 'Weight', value: '0.8 kg (pair)' },
      { label: 'Origin', value: 'Patan, Nepal' },
      { label: 'Includes', value: 'Cloth pouch' },
    ],
    features: ['Hand-forged bronze', 'Bright sustained tone', 'Traditional Newari design', 'Pair with cloth pouch'],
    inStock: true,
    artisan: 'Surya Prasad Sharma',
    region: 'Patan',
  },
  {
    id: 'p014',
    name: 'Guitar Capo — Brass Spring-Loaded',
    slug: 'guitar-capo-brass-spring-loaded',
    category: 'Accessories',
    subcategory: 'Guitar Accessories',
    price: 650,
    originalPrice: 900,
    rating: 4.5,
    reviewCount: 421,
    images: [
      'https://images.unsplash.com/photo-1672578249566-3f4b6d564aa2?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A durable brass spring-loaded capo for acoustic and electric guitars. Fits most neck profiles and provides clean, buzz-free fretting. Padded contact points protect your instrument\'s finish.',
    specs: [
      { label: 'Material', value: 'Brass, silicone pad' },
      { label: 'Fits', value: '6-string guitars' },
      { label: 'Mechanism', value: 'Spring-loaded' },
      { label: 'Weight', value: '60g' },
    ],
    features: ['Solid brass construction', 'Silicone padding', 'Spring-loaded mechanism', 'Fits 6-string guitars'],
    badge: 'sale',
    inStock: true,
  },
  {
    id: 'p015',
    name: 'Sarangi Bow — Horsehair Professional',
    slug: 'sarangi-bow-horsehair-professional',
    category: 'Accessories',
    subcategory: 'Bows',
    price: 1800,
    rating: 4.7,
    reviewCount: 38,
    images: [
      'https://images.unsplash.com/photo-1646765444015-5881f0fab3e8?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A professional sarangi bow made from premium horsehair and seasoned wood. Properly balanced for smooth bowing and responsive control. Hand-fitted with an adjustable frog for tension adjustment.',
    specs: [
      { label: 'Material', value: 'Seasoned wood, horsehair' },
      { label: 'Length', value: '22 inches (56 cm)' },
      { label: 'Frog', value: 'Wood, adjustable' },
      { label: 'Hair', value: 'Natural horsehair' },
    ],
    features: ['Premium horsehair', 'Seasoned wood stick', 'Adjustable tension frog', 'Professional balance'],
    inStock: true,
  },
  {
    id: 'p016',
    name: 'Damphu — Tamang Traditional Drum',
    slug: 'damphu-tamang-traditional-drum',
    category: 'Traditional Instruments',
    subcategory: 'Folk Drums',
    price: 3500,
    rating: 4.6,
    reviewCount: 29,
    images: [
      'https://images.unsplash.com/photo-1721179389414-8c3f507e2bc2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1530917203633-106d4a1a0967?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'The Damphu is the traditional drum of the Tamang people of Nepal. Made from a hollowed wooden cylinder with a single goat-skin head and an internal tuning mechanism using bamboo pegs. Produces a warm, rhythmic tone central to Tamang folk music and dance.',
    specs: [
      { label: 'Material', value: 'Hollowed wood, goat skin' },
      { label: 'Diameter', value: '10 inches (25 cm)' },
      { label: 'Depth', value: '6 inches (15 cm)' },
      { label: 'Tuning', value: 'Bamboo pegs' },
      { label: 'Origin', value: 'Nuwakot, Nepal' },
      { label: 'Includes', value: 'Strap, tuning guide' },
    ],
    features: ['Traditional Tamang design', 'Bamboo peg tuning', 'Goat skin head', 'Hand-carved body'],
    badge: 'new',
    inStock: true,
    artisan: 'Hari Bahadur Magar',
    region: 'Nuwakot',
  },
  {
    id: 'p017',
    name: 'Concert Ukulele — Ten Size Koa Wood',
    slug: 'concert-ukulele-ten-size-koa-wood',
    category: 'Guitars',
    subcategory: 'Ukuleles',
    price: 5200,
    originalPrice: 6500,
    rating: 4.9,
    reviewCount: 156,
    images: [
      'https://images.unsplash.com/photo-1707699164633-0e584b2da329?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1672578249566-3f4b6d564aa2?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A concert-size ukulele crafted from beautiful koa wood with stunning grain patterns. Warm, rich tone with excellent sustain. Features a rosewood fingerboard, bone nut and saddle, and quality geared tuners for stable tuning.',
    specs: [
      { label: 'Top', value: 'Solid koa wood' },
      { label: 'Body', value: 'Koa wood' },
      { label: 'Fingerboard', value: 'Rosewood' },
      { label: 'Scale Length', value: '15 inches (concert)' },
      { label: 'Nut/Saddle', value: 'Bone' },
      { label: 'Includes', value: 'Padded gig bag, tuner' },
    ],
    features: ['Solid koa wood top', 'Concert size body', 'Bone nut and saddle', 'Geared tuners'],
    badge: 'trending',
    inStock: true,
    artisan: 'Bishnu Gurung',
    region: 'Pokhara',
  },
  {
    id: 'p018',
    name: 'Electric Guitar — ST Style Solid Body',
    slug: 'electric-guitar-st-style-solid-body',
    category: 'Guitars',
    subcategory: 'Electric Guitars',
    price: 11500,
    rating: 4.6,
    reviewCount: 89,
    images: [
      'https://images.unsplash.com/photo-1514649923863-ceaf75b7ec00?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1672578249566-3f4b6d564aa2?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A versatile ST-style electric guitar with a solid alder body, maple neck, and rosewood fingerboard. Three single-coil pickups with a 5-way selector deliver everything from clean, bright tones to punchy, driven sounds. Includes a gig bag and cable.',
    specs: [
      { label: 'Body', value: 'Alder' },
      { label: 'Neck', value: 'Maple, bolt-on' },
      { label: 'Fingerboard', value: 'Rosewood, 22 frets' },
      { label: 'Pickups', value: '3 single-coil' },
      { label: 'Bridge', value: 'Tremolo, vintage style' },
      { label: 'Includes', value: 'Gig bag, cable, picks' },
    ],
    features: ['Alder solid body', '3 single-coil pickups', '5-way pickup selector', 'Tremolo bridge'],
    inStock: true,
    artisan: 'Bishnu Gurung',
    region: 'Pokhara',
  },
  {
    id: 'p019',
name: 'Panche Baja Trumpet — Nepali Folk Wind',
    slug: 'panche-baja-trumpet-nepali-folk-wind',
    category: 'Wind Instruments',
    subcategory: 'Brass',
    price: 2800,
    rating: 4.4,
    reviewCount: 31,
    images: [
      'https://images.unsplash.com/photo-1672578249566-3f4b6d564aa2?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'A traditional Nepali folk trumpet used in the Panche Baja ensemble — the ceremonial band played at weddings and festivals across rural Nepal. Hand-crafted from brass with a long, curved bell that produces a powerful, resonant call.',
    specs: [
      { label: 'Material', value: 'Brass' },
      { label: 'Length', value: '36 inches (extended)' },
      { label: 'Bell', value: 'Curved, hand-hammered' },
      { label: 'Origin', value: 'Gorkha, Nepal' },
      { label: 'Includes', value: 'Mouthpiece, cloth bag' },
    ],
    features: ['Hand-hammered brass bell', 'Traditional Panche Baja design', 'Powerful resonant tone', 'Ceremonial use'],
    inStock: true,
    artisan: 'Mohan Krishna Rai',
    region: 'Gorkha',
  },
  {
    id: 'p020',
    name: 'Guitar Strings — Acoustic Bronze 12-53',
    slug: 'guitar-strings-acoustic-bronze-12-53',
    category: 'Accessories',
    subcategory: 'Strings',
    price: 450,
    originalPrice: 600,
    rating: 4.7,
    reviewCount: 512,
    images: [
      'https://images.unsplash.com/photo-1672578249566-3f4b6d564aa2?auto=format&fit=crop&w=800&q=80',
    ],
    description:
      'High-quality phosphor bronze acoustic guitar strings (12-53 gauge). Bright, balanced tone with long-lasting corrosion resistance. Engineered for excellent intonation and smooth feel.',
    specs: [
      { label: 'Gauge', value: '12-53 (light)' },
      { label: 'Material', value: 'Phosphor bronze' },
      { label: 'Coating', value: 'Anti-corrosion' },
      { label: 'Pack', value: '3 sets' },
    ],
    features: ['Phosphor bronze alloy', 'Anti-corrosion coating', 'Bright balanced tone', '3-pack value set'],
    badge: 'sale',
    inStock: true,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-2026-001',
    customerName: 'Aarav Sharma',
    email: 'aarav.sharma@gmail.com',
    phone: '+977-9801234567',
    address: 'Thamel, Kathmandu, Bagmati',
    items: [{ product: PRODUCTS[0], quantity: 1 }],
    total: 4500,
    status: 'delivered',
    date: '2026-07-10',
    paymentMethod: 'Cash on Delivery',
  },
  {
    id: 'ORD-2026-002',
    customerName: 'Priya Gurung',
    email: 'priya.gurung@gmail.com',
    phone: '+977-9812345678',
    address: 'Lakeside, Pokhara, Gandaki',
    items: [{ product: PRODUCTS[1], quantity: 1 }, { product: PRODUCTS[14], quantity: 1 }],
    total: 10700,
    status: 'shipped',
    date: '2026-07-11',
    paymentMethod: 'Cash on Delivery',
  },
  {
    id: 'ORD-2026-003',
    customerName: 'Bishal Thapa',
    email: 'bishal.thapa@gmail.com',
    phone: '+977-9823456789',
    address: 'Baneshwor, Kathmandu, Bagmati',
    items: [{ product: PRODUCTS[5], quantity: 2 }],
    total: 7600,
    status: 'processing',
    date: '2026-07-12',
    paymentMethod: 'Cash on Delivery',
  },
  {
    id: 'ORD-2026-004',
    customerName: 'Sita Tamang',
    email: 'sita.tamang@gmail.com',
    phone: '+977-9834567890',
    address: 'Dharan, Sunsari, Koshi',
    items: [{ product: PRODUCTS[8], quantity: 3 }],
    total: 3600,
    status: 'pending',
    date: '2026-07-13',
    paymentMethod: 'Cash on Delivery',
  },
  {
    id: 'ORD-2026-005',
    customerName: 'Rohan K.C.',
    email: 'rohan.kc@gmail.com',
    phone: '+977-9845678901',
    address: 'Bhotahity, Kathmandu, Bagmati',
    items: [{ product: PRODUCTS[3], quantity: 1 }],
    total: 18500,
    status: 'pending',
    date: '2026-07-13',
    paymentMethod: 'Cash on Delivery',
  },
];

export const MOCK_INQUIRIES: WholesaleInquiry[] = [
  {
    id: 'WI-001',
    businessName: 'Himalayan Music Store',
    contactName: 'Dipak Adhikari',
    email: 'dipak@himalayanmusic.com',
    phone: '+977-9801111222',
    city: 'Kathmandu',
    products: ['Madal', 'Sarangi', 'Tungna'],
    quantity: '20-50 units per month',
    message: 'We are looking for a reliable supplier of traditional Nepali instruments for our retail store. Please send us your wholesale catalog and pricing.',
    status: 'new',
    date: '2026-07-12',
  },
  {
    id: 'WI-002',
    businessName: 'Newari Crafts Collective',
    contactName: 'Sunita Shrestha',
    email: 'sunita@newaricrafts.com',
    phone: '+977-9812222333',
    city: 'Patan',
    products: ['Dholak', 'Jhyali', 'Harmonium'],
    quantity: '15-30 units per quarter',
    message: 'Interested in bulk orders for our cultural center. Need instruments for teaching and performance.',
    status: 'contacted',
    date: '2026-07-10',
  },
  {
    id: 'WI-003',
    businessName: 'Everest Exports',
    contactName: 'Karma Sherpa',
    email: 'karma@everestexports.com',
    phone: '+977-9823333444',
    city: 'Namche Bazaar',
    products: ['Ukulele', 'Flute', 'Damphu'],
    quantity: '50-100 units per month',
    message: 'We export Nepali handicrafts to international markets. Looking for high-quality instruments with consistent supply.',
    status: 'new',
    date: '2026-07-13',
  },
];
